[package]
name = "ImageMagickTest"
version = "0.1.0"
edition = "2024"

[dependencies]
circular-buffer = "1.1.0"
magick_rust = "1.0.0"
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
